# Generated by Django 3.0.7 on 2020-06-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='stats',
            new_name='status',
        ),
    ]
